qianfanmall:
  env:
    domain: https://dev.yys.lingyiqianfan.com
    ssl:
      enabled: true
      key-store-password: your-keystore-password  # 请替换为实际的SSL证书密码
      key-store: dev.yys.lingyiqianfan.com.jks  # SSL证书文件名
    subscription-notice:
      cert-domain-name: dev.yys
      cert-expired-time: 2026-03-27  # 请更新为证书实际过期时间
  storage-path: storage
