package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallRole;
import com.lyqf.qianfanmall.db.domain.QianfanmallRoleExample;

public interface QianfanmallRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    int insert(QianfanmallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    QianfanmallRole selectOneByExample(QianfanmallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    QianfanmallRole selectOneByExampleSelective(@Param("example") QianfanmallRoleExample example, @Param("selective") QianfanmallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    List<QianfanmallRole> selectByExampleSelective(@Param("example") QianfanmallRoleExample example, @Param("selective") QianfanmallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    List<QianfanmallRole> selectByExample(QianfanmallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    QianfanmallRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    QianfanmallRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    QianfanmallRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallRole record, @Param("example") QianfanmallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallRole record, @Param("example") QianfanmallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}