package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallUser;
import com.lyqf.qianfanmall.db.domain.QianfanmallUserExample;

public interface QianfanmallUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    int insert(QianfanmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    QianfanmallUser selectOneByExample(QianfanmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    QianfanmallUser selectOneByExampleSelective(@Param("example") QianfanmallUserExample example, @Param("selective") QianfanmallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    List<QianfanmallUser> selectByExampleSelective(@Param("example") QianfanmallUserExample example, @Param("selective") QianfanmallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    List<QianfanmallUser> selectByExample(QianfanmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    QianfanmallUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    QianfanmallUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    QianfanmallUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallUser record, @Param("example") QianfanmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallUser record, @Param("example") QianfanmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}