package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallKeyword;
import com.lyqf.qianfanmall.db.domain.QianfanmallKeywordExample;

public interface QianfanmallKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    int insert(QianfanmallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    QianfanmallKeyword selectOneByExample(QianfanmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    QianfanmallKeyword selectOneByExampleSelective(@Param("example") QianfanmallKeywordExample example, @Param("selective") QianfanmallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    List<QianfanmallKeyword> selectByExampleSelective(@Param("example") QianfanmallKeywordExample example, @Param("selective") QianfanmallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    List<QianfanmallKeyword> selectByExample(QianfanmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    QianfanmallKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    QianfanmallKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    QianfanmallKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallKeyword record, @Param("example") QianfanmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallKeyword record, @Param("example") QianfanmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}