package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallRegion;
import com.lyqf.qianfanmall.db.domain.QianfanmallRegionExample;

public interface QianfanmallRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    int insert(QianfanmallRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    QianfanmallRegion selectOneByExample(QianfanmallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    QianfanmallRegion selectOneByExampleSelective(@Param("example") QianfanmallRegionExample example, @Param("selective") QianfanmallRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    List<QianfanmallRegion> selectByExampleSelective(@Param("example") QianfanmallRegionExample example, @Param("selective") QianfanmallRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    List<QianfanmallRegion> selectByExample(QianfanmallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    QianfanmallRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    QianfanmallRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallRegion record, @Param("example") QianfanmallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallRegion record, @Param("example") QianfanmallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallRegion record);
}