package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallGoods;
import com.lyqf.qianfanmall.db.domain.QianfanmallGoodsExample;

public interface QianfanmallGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    int insert(QianfanmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    QianfanmallGoods selectOneByExample(QianfanmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    QianfanmallGoods selectOneByExampleSelective(@Param("example") QianfanmallGoodsExample example, @Param("selective") QianfanmallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    QianfanmallGoods selectOneByExampleWithBLOBs(QianfanmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    List<QianfanmallGoods> selectByExampleSelective(@Param("example") QianfanmallGoodsExample example, @Param("selective") QianfanmallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    List<QianfanmallGoods> selectByExampleWithBLOBs(QianfanmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    List<QianfanmallGoods> selectByExample(QianfanmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    QianfanmallGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    QianfanmallGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    QianfanmallGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallGoods record, @Param("example") QianfanmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") QianfanmallGoods record, @Param("example") QianfanmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallGoods record, @Param("example") QianfanmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(QianfanmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}