package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallBrand;
import com.lyqf.qianfanmall.db.domain.QianfanmallBrandExample;

public interface QianfanmallBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    int insert(QianfanmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    QianfanmallBrand selectOneByExample(QianfanmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    QianfanmallBrand selectOneByExampleSelective(@Param("example") QianfanmallBrandExample example, @Param("selective") QianfanmallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    List<QianfanmallBrand> selectByExampleSelective(@Param("example") QianfanmallBrandExample example, @Param("selective") QianfanmallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    List<QianfanmallBrand> selectByExample(QianfanmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    QianfanmallBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    QianfanmallBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    QianfanmallBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallBrand record, @Param("example") QianfanmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallBrand record, @Param("example") QianfanmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}