package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallGoodsSpecification;
import com.lyqf.qianfanmall.db.domain.QianfanmallGoodsSpecificationExample;

public interface QianfanmallGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    int insert(QianfanmallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    QianfanmallGoodsSpecification selectOneByExample(QianfanmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    QianfanmallGoodsSpecification selectOneByExampleSelective(@Param("example") QianfanmallGoodsSpecificationExample example, @Param("selective") QianfanmallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    List<QianfanmallGoodsSpecification> selectByExampleSelective(@Param("example") QianfanmallGoodsSpecificationExample example, @Param("selective") QianfanmallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    List<QianfanmallGoodsSpecification> selectByExample(QianfanmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    QianfanmallGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    QianfanmallGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    QianfanmallGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallGoodsSpecification record, @Param("example") QianfanmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallGoodsSpecification record, @Param("example") QianfanmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}