package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallCouponUser;
import com.lyqf.qianfanmall.db.domain.QianfanmallCouponUserExample;

public interface QianfanmallCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    int insert(QianfanmallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    QianfanmallCouponUser selectOneByExample(QianfanmallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    QianfanmallCouponUser selectOneByExampleSelective(@Param("example") QianfanmallCouponUserExample example, @Param("selective") QianfanmallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    List<QianfanmallCouponUser> selectByExampleSelective(@Param("example") QianfanmallCouponUserExample example, @Param("selective") QianfanmallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    List<QianfanmallCouponUser> selectByExample(QianfanmallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    QianfanmallCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    QianfanmallCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    QianfanmallCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallCouponUser record, @Param("example") QianfanmallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallCouponUser record, @Param("example") QianfanmallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}