package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallAd;
import com.lyqf.qianfanmall.db.domain.QianfanmallAdExample;

public interface QianfanmallAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    int insert(QianfanmallAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    QianfanmallAd selectOneByExample(QianfanmallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    QianfanmallAd selectOneByExampleSelective(@Param("example") QianfanmallAdExample example, @Param("selective") QianfanmallAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    List<QianfanmallAd> selectByExampleSelective(@Param("example") QianfanmallAdExample example, @Param("selective") QianfanmallAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    List<QianfanmallAd> selectByExample(QianfanmallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    QianfanmallAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    QianfanmallAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    QianfanmallAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallAd record, @Param("example") QianfanmallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallAd record, @Param("example") QianfanmallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}