package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallGroupon;
import com.lyqf.qianfanmall.db.domain.QianfanmallGrouponExample;

public interface QianfanmallGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    int insert(QianfanmallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    QianfanmallGroupon selectOneByExample(QianfanmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    QianfanmallGroupon selectOneByExampleSelective(@Param("example") QianfanmallGrouponExample example, @Param("selective") QianfanmallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    List<QianfanmallGroupon> selectByExampleSelective(@Param("example") QianfanmallGrouponExample example, @Param("selective") QianfanmallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    List<QianfanmallGroupon> selectByExample(QianfanmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    QianfanmallGroupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    QianfanmallGroupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    QianfanmallGroupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallGroupon record, @Param("example") QianfanmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallGroupon record, @Param("example") QianfanmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}