package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallOrderGoods;
import com.lyqf.qianfanmall.db.domain.QianfanmallOrderGoodsExample;

public interface QianfanmallOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    int insert(QianfanmallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    QianfanmallOrderGoods selectOneByExample(QianfanmallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    QianfanmallOrderGoods selectOneByExampleSelective(@Param("example") QianfanmallOrderGoodsExample example, @Param("selective") QianfanmallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    List<QianfanmallOrderGoods> selectByExampleSelective(@Param("example") QianfanmallOrderGoodsExample example, @Param("selective") QianfanmallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    List<QianfanmallOrderGoods> selectByExample(QianfanmallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    QianfanmallOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    QianfanmallOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    QianfanmallOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallOrderGoods record, @Param("example") QianfanmallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallOrderGoods record, @Param("example") QianfanmallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}