package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallStorage;
import com.lyqf.qianfanmall.db.domain.QianfanmallStorageExample;

public interface QianfanmallStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    int insert(QianfanmallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    QianfanmallStorage selectOneByExample(QianfanmallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    QianfanmallStorage selectOneByExampleSelective(@Param("example") QianfanmallStorageExample example, @Param("selective") QianfanmallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    List<QianfanmallStorage> selectByExampleSelective(@Param("example") QianfanmallStorageExample example, @Param("selective") QianfanmallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    List<QianfanmallStorage> selectByExample(QianfanmallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    QianfanmallStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    QianfanmallStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    QianfanmallStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallStorage record, @Param("example") QianfanmallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallStorage record, @Param("example") QianfanmallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}