package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallCollect;
import com.lyqf.qianfanmall.db.domain.QianfanmallCollectExample;

public interface QianfanmallCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    int insert(QianfanmallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    QianfanmallCollect selectOneByExample(QianfanmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    QianfanmallCollect selectOneByExampleSelective(@Param("example") QianfanmallCollectExample example, @Param("selective") QianfanmallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    List<QianfanmallCollect> selectByExampleSelective(@Param("example") QianfanmallCollectExample example, @Param("selective") QianfanmallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    List<QianfanmallCollect> selectByExample(QianfanmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    QianfanmallCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    QianfanmallCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    QianfanmallCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallCollect record, @Param("example") QianfanmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallCollect record, @Param("example") QianfanmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}