package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallCart;
import com.lyqf.qianfanmall.db.domain.QianfanmallCartExample;

public interface QianfanmallCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    int insert(QianfanmallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    QianfanmallCart selectOneByExample(QianfanmallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    QianfanmallCart selectOneByExampleSelective(@Param("example") QianfanmallCartExample example, @Param("selective") QianfanmallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    List<QianfanmallCart> selectByExampleSelective(@Param("example") QianfanmallCartExample example, @Param("selective") QianfanmallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    List<QianfanmallCart> selectByExample(QianfanmallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    QianfanmallCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    QianfanmallCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    QianfanmallCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallCart record, @Param("example") QianfanmallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallCart record, @Param("example") QianfanmallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}