package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallComment;
import com.lyqf.qianfanmall.db.domain.QianfanmallCommentExample;

public interface QianfanmallCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    int insert(QianfanmallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    QianfanmallComment selectOneByExample(QianfanmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    QianfanmallComment selectOneByExampleSelective(@Param("example") QianfanmallCommentExample example, @Param("selective") QianfanmallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    List<QianfanmallComment> selectByExampleSelective(@Param("example") QianfanmallCommentExample example, @Param("selective") QianfanmallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    List<QianfanmallComment> selectByExample(QianfanmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    QianfanmallComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    QianfanmallComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    QianfanmallComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallComment record, @Param("example") QianfanmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallComment record, @Param("example") QianfanmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}