package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallSystem;
import com.lyqf.qianfanmall.db.domain.QianfanmallSystemExample;

public interface QianfanmallSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    int insert(QianfanmallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    QianfanmallSystem selectOneByExample(QianfanmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    QianfanmallSystem selectOneByExampleSelective(@Param("example") QianfanmallSystemExample example, @Param("selective") QianfanmallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    List<QianfanmallSystem> selectByExampleSelective(@Param("example") QianfanmallSystemExample example, @Param("selective") QianfanmallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    List<QianfanmallSystem> selectByExample(QianfanmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    QianfanmallSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    QianfanmallSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    QianfanmallSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallSystem record, @Param("example") QianfanmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallSystem record, @Param("example") QianfanmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}