package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallCategory;
import com.lyqf.qianfanmall.db.domain.QianfanmallCategoryExample;

public interface QianfanmallCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    int insert(QianfanmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    QianfanmallCategory selectOneByExample(QianfanmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    QianfanmallCategory selectOneByExampleSelective(@Param("example") QianfanmallCategoryExample example, @Param("selective") QianfanmallCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    List<QianfanmallCategory> selectByExampleSelective(@Param("example") QianfanmallCategoryExample example, @Param("selective") QianfanmallCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    List<QianfanmallCategory> selectByExample(QianfanmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    QianfanmallCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    QianfanmallCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    QianfanmallCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallCategory record, @Param("example") QianfanmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallCategory record, @Param("example") QianfanmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}