package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallPermission;
import com.lyqf.qianfanmall.db.domain.QianfanmallPermissionExample;

public interface QianfanmallPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    int insert(QianfanmallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    QianfanmallPermission selectOneByExample(QianfanmallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    QianfanmallPermission selectOneByExampleSelective(@Param("example") QianfanmallPermissionExample example, @Param("selective") QianfanmallPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    List<QianfanmallPermission> selectByExampleSelective(@Param("example") QianfanmallPermissionExample example, @Param("selective") QianfanmallPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    List<QianfanmallPermission> selectByExample(QianfanmallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    QianfanmallPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    QianfanmallPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    QianfanmallPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallPermission record, @Param("example") QianfanmallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallPermission record, @Param("example") QianfanmallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}