package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallLog;
import com.lyqf.qianfanmall.db.domain.QianfanmallLogExample;

public interface QianfanmallLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    int insert(QianfanmallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    QianfanmallLog selectOneByExample(QianfanmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    QianfanmallLog selectOneByExampleSelective(@Param("example") QianfanmallLogExample example, @Param("selective") QianfanmallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    List<QianfanmallLog> selectByExampleSelective(@Param("example") QianfanmallLogExample example, @Param("selective") QianfanmallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    List<QianfanmallLog> selectByExample(QianfanmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    QianfanmallLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    QianfanmallLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    QianfanmallLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallLog record, @Param("example") QianfanmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallLog record, @Param("example") QianfanmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}