package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallTopic;
import com.lyqf.qianfanmall.db.domain.QianfanmallTopicExample;

public interface QianfanmallTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    int insert(QianfanmallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    QianfanmallTopic selectOneByExample(QianfanmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    QianfanmallTopic selectOneByExampleSelective(@Param("example") QianfanmallTopicExample example, @Param("selective") QianfanmallTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    QianfanmallTopic selectOneByExampleWithBLOBs(QianfanmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    List<QianfanmallTopic> selectByExampleSelective(@Param("example") QianfanmallTopicExample example, @Param("selective") QianfanmallTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    List<QianfanmallTopic> selectByExampleWithBLOBs(QianfanmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    List<QianfanmallTopic> selectByExample(QianfanmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    QianfanmallTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    QianfanmallTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    QianfanmallTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallTopic record, @Param("example") QianfanmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") QianfanmallTopic record, @Param("example") QianfanmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallTopic record, @Param("example") QianfanmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(QianfanmallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}