package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallNoticeAdmin;
import com.lyqf.qianfanmall.db.domain.QianfanmallNoticeAdminExample;

public interface QianfanmallNoticeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    int insert(QianfanmallNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    QianfanmallNoticeAdmin selectOneByExample(QianfanmallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    QianfanmallNoticeAdmin selectOneByExampleSelective(@Param("example") QianfanmallNoticeAdminExample example, @Param("selective") QianfanmallNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    List<QianfanmallNoticeAdmin> selectByExampleSelective(@Param("example") QianfanmallNoticeAdminExample example, @Param("selective") QianfanmallNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    List<QianfanmallNoticeAdmin> selectByExample(QianfanmallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    QianfanmallNoticeAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    QianfanmallNoticeAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    QianfanmallNoticeAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallNoticeAdmin record, @Param("example") QianfanmallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallNoticeAdmin record, @Param("example") QianfanmallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}