package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallSearchHistory;
import com.lyqf.qianfanmall.db.domain.QianfanmallSearchHistoryExample;

public interface QianfanmallSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    int insert(QianfanmallSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    QianfanmallSearchHistory selectOneByExample(QianfanmallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    QianfanmallSearchHistory selectOneByExampleSelective(@Param("example") QianfanmallSearchHistoryExample example, @Param("selective") QianfanmallSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    List<QianfanmallSearchHistory> selectByExampleSelective(@Param("example") QianfanmallSearchHistoryExample example, @Param("selective") QianfanmallSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    List<QianfanmallSearchHistory> selectByExample(QianfanmallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    QianfanmallSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    QianfanmallSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    QianfanmallSearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallSearchHistory record, @Param("example") QianfanmallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallSearchHistory record, @Param("example") QianfanmallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}