package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallFootprint;
import com.lyqf.qianfanmall.db.domain.QianfanmallFootprintExample;

public interface QianfanmallFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    int insert(QianfanmallFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    QianfanmallFootprint selectOneByExample(QianfanmallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    QianfanmallFootprint selectOneByExampleSelective(@Param("example") QianfanmallFootprintExample example, @Param("selective") QianfanmallFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    List<QianfanmallFootprint> selectByExampleSelective(@Param("example") QianfanmallFootprintExample example, @Param("selective") QianfanmallFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    List<QianfanmallFootprint> selectByExample(QianfanmallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    QianfanmallFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    QianfanmallFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    QianfanmallFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallFootprint record, @Param("example") QianfanmallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallFootprint record, @Param("example") QianfanmallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}