package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallGoodsProduct;
import com.lyqf.qianfanmall.db.domain.QianfanmallGoodsProductExample;

public interface QianfanmallGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    int insert(QianfanmallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    QianfanmallGoodsProduct selectOneByExample(QianfanmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    QianfanmallGoodsProduct selectOneByExampleSelective(@Param("example") QianfanmallGoodsProductExample example, @Param("selective") QianfanmallGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    List<QianfanmallGoodsProduct> selectByExampleSelective(@Param("example") QianfanmallGoodsProductExample example, @Param("selective") QianfanmallGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    List<QianfanmallGoodsProduct> selectByExample(QianfanmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    QianfanmallGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    QianfanmallGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    QianfanmallGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallGoodsProduct record, @Param("example") QianfanmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallGoodsProduct record, @Param("example") QianfanmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}