package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallAftersale;
import com.lyqf.qianfanmall.db.domain.QianfanmallAftersaleExample;

public interface QianfanmallAftersaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    int insert(QianfanmallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    QianfanmallAftersale selectOneByExample(QianfanmallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    QianfanmallAftersale selectOneByExampleSelective(@Param("example") QianfanmallAftersaleExample example, @Param("selective") QianfanmallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    List<QianfanmallAftersale> selectByExampleSelective(@Param("example") QianfanmallAftersaleExample example, @Param("selective") QianfanmallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    List<QianfanmallAftersale> selectByExample(QianfanmallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    QianfanmallAftersale selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    QianfanmallAftersale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    QianfanmallAftersale selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallAftersale record, @Param("example") QianfanmallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallAftersale record, @Param("example") QianfanmallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}