package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallAddress;
import com.lyqf.qianfanmall.db.domain.QianfanmallAddressExample;

public interface QianfanmallAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    int insert(QianfanmallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    QianfanmallAddress selectOneByExample(QianfanmallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    QianfanmallAddress selectOneByExampleSelective(@Param("example") QianfanmallAddressExample example, @Param("selective") QianfanmallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    List<QianfanmallAddress> selectByExampleSelective(@Param("example") QianfanmallAddressExample example, @Param("selective") QianfanmallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    List<QianfanmallAddress> selectByExample(QianfanmallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    QianfanmallAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    QianfanmallAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    QianfanmallAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallAddress record, @Param("example") QianfanmallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallAddress record, @Param("example") QianfanmallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_address
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}