package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallCoupon;
import com.lyqf.qianfanmall.db.domain.QianfanmallCouponExample;

public interface QianfanmallCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    int insert(QianfanmallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    QianfanmallCoupon selectOneByExample(QianfanmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    QianfanmallCoupon selectOneByExampleSelective(@Param("example") QianfanmallCouponExample example, @Param("selective") QianfanmallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    List<QianfanmallCoupon> selectByExampleSelective(@Param("example") QianfanmallCouponExample example, @Param("selective") QianfanmallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    List<QianfanmallCoupon> selectByExample(QianfanmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    QianfanmallCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    QianfanmallCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    QianfanmallCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallCoupon record, @Param("example") QianfanmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallCoupon record, @Param("example") QianfanmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}