package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallGrouponRules;
import com.lyqf.qianfanmall.db.domain.QianfanmallGrouponRulesExample;

public interface QianfanmallGrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    int insert(QianfanmallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    QianfanmallGrouponRules selectOneByExample(QianfanmallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    QianfanmallGrouponRules selectOneByExampleSelective(@Param("example") QianfanmallGrouponRulesExample example, @Param("selective") QianfanmallGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    List<QianfanmallGrouponRules> selectByExampleSelective(@Param("example") QianfanmallGrouponRulesExample example, @Param("selective") QianfanmallGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    List<QianfanmallGrouponRules> selectByExample(QianfanmallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    QianfanmallGrouponRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    QianfanmallGrouponRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    QianfanmallGrouponRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallGrouponRules record, @Param("example") QianfanmallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallGrouponRules record, @Param("example") QianfanmallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}