package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallGoodsAttribute;
import com.lyqf.qianfanmall.db.domain.QianfanmallGoodsAttributeExample;

public interface QianfanmallGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    int insert(QianfanmallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    QianfanmallGoodsAttribute selectOneByExample(QianfanmallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    QianfanmallGoodsAttribute selectOneByExampleSelective(@Param("example") QianfanmallGoodsAttributeExample example, @Param("selective") QianfanmallGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    List<QianfanmallGoodsAttribute> selectByExampleSelective(@Param("example") QianfanmallGoodsAttributeExample example, @Param("selective") QianfanmallGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    List<QianfanmallGoodsAttribute> selectByExample(QianfanmallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    QianfanmallGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    QianfanmallGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    QianfanmallGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallGoodsAttribute record, @Param("example") QianfanmallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallGoodsAttribute record, @Param("example") QianfanmallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}