package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallOrder;
import com.lyqf.qianfanmall.db.domain.QianfanmallOrderExample;

public interface QianfanmallOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    int insert(QianfanmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    QianfanmallOrder selectOneByExample(QianfanmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    QianfanmallOrder selectOneByExampleSelective(@Param("example") QianfanmallOrderExample example, @Param("selective") QianfanmallOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    List<QianfanmallOrder> selectByExampleSelective(@Param("example") QianfanmallOrderExample example, @Param("selective") QianfanmallOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    List<QianfanmallOrder> selectByExample(QianfanmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    QianfanmallOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    QianfanmallOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    QianfanmallOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallOrder record, @Param("example") QianfanmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallOrder record, @Param("example") QianfanmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}