package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallIssue;
import com.lyqf.qianfanmall.db.domain.QianfanmallIssueExample;

public interface QianfanmallIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    int insert(QianfanmallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    QianfanmallIssue selectOneByExample(QianfanmallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    QianfanmallIssue selectOneByExampleSelective(@Param("example") QianfanmallIssueExample example, @Param("selective") QianfanmallIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    List<QianfanmallIssue> selectByExampleSelective(@Param("example") QianfanmallIssueExample example, @Param("selective") QianfanmallIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    List<QianfanmallIssue> selectByExample(QianfanmallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    QianfanmallIssue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    QianfanmallIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    QianfanmallIssue selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallIssue record, @Param("example") QianfanmallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallIssue record, @Param("example") QianfanmallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}