package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallFeedback;
import com.lyqf.qianfanmall.db.domain.QianfanmallFeedbackExample;

public interface QianfanmallFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    int insert(QianfanmallFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    QianfanmallFeedback selectOneByExample(QianfanmallFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    QianfanmallFeedback selectOneByExampleSelective(@Param("example") QianfanmallFeedbackExample example, @Param("selective") QianfanmallFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    List<QianfanmallFeedback> selectByExampleSelective(@Param("example") QianfanmallFeedbackExample example, @Param("selective") QianfanmallFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    List<QianfanmallFeedback> selectByExample(QianfanmallFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    QianfanmallFeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    QianfanmallFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    QianfanmallFeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallFeedback record, @Param("example") QianfanmallFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallFeedback record, @Param("example") QianfanmallFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}