package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallAdmin;
import com.lyqf.qianfanmall.db.domain.QianfanmallAdminExample;

public interface QianfanmallAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    int insert(QianfanmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    QianfanmallAdmin selectOneByExample(QianfanmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    QianfanmallAdmin selectOneByExampleSelective(@Param("example") QianfanmallAdminExample example, @Param("selective") QianfanmallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    List<QianfanmallAdmin> selectByExampleSelective(@Param("example") QianfanmallAdminExample example, @Param("selective") QianfanmallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    List<QianfanmallAdmin> selectByExample(QianfanmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    QianfanmallAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    QianfanmallAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    QianfanmallAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallAdmin record, @Param("example") QianfanmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallAdmin record, @Param("example") QianfanmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}