package com.lyqf.qianfanmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lyqf.qianfanmall.db.domain.QianfanmallNotice;
import com.lyqf.qianfanmall.db.domain.QianfanmallNoticeExample;

public interface QianfanmallNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    long countByExample(QianfanmallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    int deleteByExample(QianfanmallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    int insert(QianfanmallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    int insertSelective(QianfanmallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    QianfanmallNotice selectOneByExample(QianfanmallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    QianfanmallNotice selectOneByExampleSelective(@Param("example") QianfanmallNoticeExample example, @Param("selective") QianfanmallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    List<QianfanmallNotice> selectByExampleSelective(@Param("example") QianfanmallNoticeExample example, @Param("selective") QianfanmallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    List<QianfanmallNotice> selectByExample(QianfanmallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    QianfanmallNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") QianfanmallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    QianfanmallNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    QianfanmallNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QianfanmallNotice record, @Param("example") QianfanmallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QianfanmallNotice record, @Param("example") QianfanmallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QianfanmallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QianfanmallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") QianfanmallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qianfanmall_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}